### PR TITLE
Added --user-sites flag

### PR DESCRIPTION
**Pull request by Cobertos**
No tests, haven't run through mypy, but tested on my machine and `--site=stackoverflow`, `--all-sites` and `--user-sites` all work.

Note, `--user-sites` will require an `access_token`, as it needs to access `/me/associated-users`, otherwise you get a 401 error.

Also `/me/associated-users` doesn't return site API stems (like `/sites` does), so it has to do a little bit of fuckery to match the `site_name` field to the `name` field, also removing ` Stack Exchange` suffix. The only mapping in my accounts that didn't map was `Meta Stack Exchange`, otherwise I was able to get quite a few

image

### CODE REVIEW

**Comment by Cobertos** [comment]
Mypy types should be fixed

**Comment by ankostis** [comment]
If i get it right, what's the use of keeping `--all`,
and not replace it with `--user-sites`?

**Comment by Cobertos** [comment]
Not much that I can see. Only debugging and backward-compatibility I can imagine. It's easy to support though just because it's just a slightly different input to `sites=`

**Comment by karlicoss** [comment]
Thanks @Cobertos ! 
@ankostis another usecase for `--all-sites` is that it doesn't require oauth `access_token`, apparently you can just register the app, get the `key` and keep `access_token` empty! Although not sure which implications it has for which data is included in the export (presumably it will only have access to 'public' data)

**Pull request merged**
